# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "message.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmessage.proto\x12\x0emessageservice"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t"z\n\x0fMessageResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.messageservice.MessageResponse.Status"/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x32\x62\n\x0eMessageService\x12P\n\x0bSendMessage\x12\x1e.messageservice.MessageRequest\x1a\x1f.messageservice.MessageResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "message_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MESSAGEREQUEST"]._serialized_start = 33
    _globals["_MESSAGEREQUEST"]._serialized_end = 66
    _globals["_MESSAGERESPONSE"]._serialized_start = 68
    _globals["_MESSAGERESPONSE"]._serialized_end = 190
    _globals["_MESSAGERESPONSE_STATUS"]._serialized_start = 143
    _globals["_MESSAGERESPONSE_STATUS"]._serialized_end = 190
    _globals["_MESSAGESERVICE"]._serialized_start = 192
    _globals["_MESSAGESERVICE"]._serialized_end = 290
# @@protoc_insertion_point(module_scope)
